version: '3.1'

services:
  broker:
    image: redis:6-alpine3.17

  api:
    build: ./api
    ports:
      - "3000:3000"
    volumes:
      - ./api:/api
    env_file:
      - .env

  workers:
    build: ./workers
    volumes:
      - ./workers:/workers
    env_file:
      - .env